### ISSUE TITLE
backup GitHub issues, comments, discussions, etc.

### ISSUE THREAD

**Issue by justinmk** [neovim/doc#16]
Potential tools:

1. ~~https://github-backup.branchable.com/~~ doesn't look maintained
    - https://hackage.haskell.org/package/github-backup
    - used by debian: https://github.com/Debian/README.Debian#tips
2. ✅ https://github.com/josegonzalez/python-github-backup good results 👍 

# Requirements

See https://github.com/neovim/doc/issues/16#issuecomment-1636881895

**Comment by Frank-Mayer** [comment]
@justinmk where should this be stored? I would suggest a GitHub Release.

**Comment by justinmk** [comment]
@Frank-Mayer I would expect the data to be stored in a git repo.

**Comment by Frank-Mayer** [comment]
@justinmk one backup-repo to back up multiple other repositories? Or one backup branch in one repository?

The first option could be useful if there are multiple different repos to back up.

**Comment by Frank-Mayer** [comment]
I would prefer the first option.

One repository `neovim/backup` with one directory for every neovim repository that should get a backup.

Using a GitHub action triggered on a cron shedule (maybe each week) these backups can be updated.

**Comment by justinmk** [comment]
Nice! Looks good to me. Don't want separate branches, only separate directories as you did.

I think these are requirements:

1. The repos should be explicitly chosen, i.e. we don't want to implicitly backup all repos. (where is that specified, I don't see it in your [gha job](https://github.com/Frank-Mayer/backup/blob/main/.github/workflows/backup.yml)?)
1. The cron job should be very friendly to github's API
    - Only incremental changes should be pulled.
1. Ignore anything newer than 1 week (1 month?). We want to avoid storing "edit history".
    - Only pull the "latest" version of a comment, not its history (assuming github API even offers that)
1. Repo size should be not too big, hopefully much less than 1 GB.
    - Don't store images/videos.
    - Other ideas?

**Comment by Frank-Mayer** [comment]
> 1. The repos should be explicitly chosen, i.e. we don't want to implicitly backup all repos. (where is that specified, I don't see it in your [gha job](https://github.com/Frank-Mayer/backup/blob/main/.github/workflows/backup.yml)?)

I currently back up [all repositories of the neovim organisation](https://github.com/orgs/neovim/repositories). I could provide a list, this is not a problem. I would suggest [neovim](https://github.com/neovim/neovim), [go-client](https://github.com/neovim/go-client), [node-client](https://github.com/neovim/node-client), [nvim-lspconfig](https://github.com/neovim/nvim-lspconfig), [pynvim](https://github.com/neovim/pynvim), [nvim.net](https://github.com/neovim/nvim.net).

> 2. The cron job should be very friendly to github's API
>    
>    * Only incremental changes should be pulled.

Then I will set the cron to once a month. Incremental changes are active.

> 3. Ignore anything newer than 1 week (1 month?). We want to avoid storing "edit history".
>    
>    * Only pull the "latest" version of a comment, not its history (assuming github API even offers that)

I don't think "ignore anything newer than 1 week (1 month?)" is possible with this. But I am looking into the tools and hopefully find a way to do this.

> 4. Repo size should be not too big, hopefully much less than 1 GB.
>    
>    * Don't store images/videos.
>    * Other ideas?

My test repository currently takes 7.8 MB.

**Comment by justinmk** [comment]
> I could provide a list, this is not a problem. I would suggest ...

After thinking more, maybe an explicit list isn't needed. Because the data for most repos will be very small, they don't have many issues/PRs. But if there's a way to _exclude_ a repo that may be needed. E.g. https://github.com/neovim/winget-pkgs is something we wouldn't want to backup, although it doesn't use PRs so even its data is small.

> I don't think "ignore anything newer than 1 week (1 month?)" is possible with this

Could be a TODO. I would guess we could add it as a feature to https://hackage.haskell.org/package/github-backup , or worst case, we could parse the JSON and filter our stuff manually before git-committing it.

**Comment by Frank-Mayer** [comment]
I made the suggested changes as far as I am able to do so with the given tools.

I would suggest transferring [Frank-Mayer/backup](https://github.com/Frank-Mayer/backup) to the Neovim organization.

With the current possibilities of [github-backup](https://pypi.org/project/github-backup/) I don't see a possibility of excluding `vim-patch` PRs. I would add this as a TODO. This could be added by a PR or fork to [github-backup](https://pypi.org/project/github-backup/).

Maybe you know this: I am uncertain whether secrets get transferred with the repository or not. A secret called `PAT` is expected. This is required to call the GitHub API.

**Comment by Frank-Mayer** [comment]
Well, the plan doesn't seem to work. 😅
<img width="1440" alt="Screenshot 2023-07-24 at 21 18 03" src="https://github.com/neovim/doc/assets/53651857/032c061a-eded-42a4-88c1-55dafa7382e9">

**Comment by justinmk** [comment]
Try transferring it to me

**Comment by justinmk** [comment]
Thanks again for getting this started! Can continue iterating at https://github.com/neovim/neovim-backup
