### ISSUE TITLE
Shellcheck scripts

### ISSUE THREAD

**Issue by 0x647262** [neovim/doc#18]
Reasoning:

I opened this issue for 3 reasons:

1. I read through this repository's shell scripts and noticed a handful of parts which could use refactoring.
2. Implementing some of `shellcheck`'s suggested fixes can prevent potential edge-case problems from manifesting themselves.
3. The main reason: I want to become more comfortable with [bot-ci](https://github.com/neovim/bot-ci)'s codebase.

---

Plan:

* Individual PRs for each script to make each set of changes much easier to review. 

---

Scope:

- [ ] ssh/ssh_wrapper.sh - Could be skipped
- [ ] ci/sync-mirrors.sh - Could be skipped
- [x] ci/doc-index.sh
- [x] ci/pvs-report.sh
- [ ] ci/translation-report.sh
- [ ] ci/assign-labels.sh
- [ ] ci/clint-errors.sh
- [ ] ci/deps-src.sh
- [ ] ci/common/neovim.sh
- [ ] ci/common/github-api.sh
- [ ] ci/common/dependencies.sh
- [ ] ci/common/deps-repo.sh
- [ ] ci/common/html.sh
- [ ] ci/common/common.sh
- [ ] ci/common/doc.sh
- [ ] ci/common/badge.sh
- [ ] ci/package-macos.sh
- [ ] ci/sync-lp-mirrors.sh
- [ ] ci/nightly.sh
- [ ] ci/vimpatch-report.sh
- [ ] ci/clang-report.sh
- [ ] ci/doxygen.sh
- [ ] ci/user-docu.sh
- [ ] scripts/travis-setup.sh

---

Thoughts?

**Comment by justinmk** [comment]
this issue is very outdated (scripts changed)
