### ISSUE TITLE
user docs: broken link

### ISSUE THREAD

**Issue by Integralist** [neovim/doc#26]
https://neovim.io/doc/user/lua.html#lua-vimscript

```
vim.cmd({command})
    See |[vim.cmd()](https://neovim.io/doc/user/vim.html)|.
```

The linked page doesn't exist:
https://neovim.io/doc/user/vim.html

**Comment by justinmk** [comment]
Thanks. Will be updating our docs generation in the next weeks, I'll review these kind of issues then.

**Comment by clason** [comment]
Seems to work now?
