### ISSUE TITLE
CCS files

### ISSUE THREAD

**Issue by hinell** [neovim/doc#32]
I request to add css files so docs can be served locally. Thanks!

**Comment by justinmk** [comment]
css lives in https://github.com/neovim/neovim.github.io/ and https://github.com/neovim/neovim/blob/126ef65e5b3ff0da68bfe166be0bb0a33664142b/scripts/gen_help_html.lua#L827

not sure what you are asking for. Are you working on automation scripts that live in https://github.com/neovim/doc ?
