### ISSUE TITLE
Autocmd section got messed up

### ISSUE THREAD

**Issue by kiyoon** [neovim/doc#35]
![image](https://user-images.githubusercontent.com/12980409/219384505-6c56d697-bab6-41ee-9ade-9d42b2a645be.png)

**Comment by justinmk** [comment]
what is messed up? The list items are not indented, but that is a known limitation.

**Comment by kiyoon** [comment]
@justinmk Hi, sorry if I wasn't clear. `BufReadCmd`, `BufReadPre`, `BufUnload`, `BufWinEnter` sections should have their own separate entry not being squashed inside the last bullet-point item.

**Comment by kiyoon** [comment]
Selected part is messed up. There's also weird `E200` and `E201` which I don't know if they should exist.

![image](https://user-images.githubusercontent.com/12980409/219421407-4b8f9cc5-264a-4802-8b75-b14cedd751bd.png)
