### ISSUE TITLE
https://neovim.io/doc/user/nvim.html is out-of-sync with https://github.com/neovim/neovim/wiki/Installing-Neovim

### ISSUE THREAD

**Issue by abentley-ssimwave** [neovim/doc#38]
The `write ++p` command produces "invalid argument" under v0.7.2.  This feature was apparently introduced in neovim 0.9.  0.7.2 was the latest I could get following the instructions for installing on ubuntu from the PPA (the ubuntu-provided one is even older).

Of course, it's fine to use such a command in documentation aimed at 0.9+ specifically.  But it's less good on a web site when not everyone is up-to-date.  At minimum, you should list a minimum version.  But ideally https://neovim.io/doc/user/nvim.html would work for commonly-used versions.

If the PPA and Ubuntu versions are too old to be supported by https://neovim.io/doc/user/nvim.html, then ideally https://github.com/neovim/neovim/wiki/Installing-Neovim would contain a warning and a recommendation to compile from source.

**Comment by abentley-ssimwave** [comment]
Or use the snap!  That has 0.9.1 at least.

**Comment by jamessan** [comment]
The website documentation tracks the latest code.  Use your local documentation to get version appropriate docs.

The neovim team has no control over third party packages.

**Comment by abentley-ssimwave** [comment]
The website documentation doesn't say what version it tracks.  It would be helpful if it did.  It does not say I should use my local documentation if I'm not using the latest-and-greatest.  Most version-specific documentation lists the applicable version, and a lot of it links to earlier versions.  e.g. https://docs.python.org/3/library/index.html or https://www.lua.org/manual/5.4/

No solution I suggested required control over third party packages.

I think it is valuable to an organization if their getting-started documentation has no immediate papercuts.

**Comment by justinmk** [comment]
> The website documentation doesn't say what version it tracks.

The footer of the help docs pages mentions the commit:

> Generated at 2023-06-19 05:27 from [8c9dab3](https://github.com/neovim/neovim/commit/8c9dab3e0d788d44c8a2fee83a6193f5955c814e)

>  Most version-specific documentation lists the applicable version, and a lot of it links to earlier versions. e.g. https://docs.python.org/3/library/index.html or https://www.lua.org/manual/5.4/

Yeah, we could put that in the right column somewhere.
