### ISSUE TITLE
Responsive design

### ISSUE THREAD

**Issue by sebastianv89** [neovim/doc#52]
The website becomes illegible in parts when the screen is too narrow.

The following screenshot of <https://neovim.io/doc/user/> demonstrates this.

![Screen Shot 2023-11-18 at 13 01 31](https://github.com/neovim/doc/assets/3017046/cf9e1419-679e-4852-b010-d37b45f3364f)

As you can see the right-hand side menu intersects with the main text.
Also the anchor label (`standard-plugin-list` in the screenshot) intersects with the text.

(I typically split my 1920 pixel wide monitor in two, which is why this 960px wide screenshot is my default view.)

**Comment by justinmk** [comment]
The old vim help is hardwrapped. Nvim-owned help pages are softwrapped and have "flow" layout, see https://neovim.io/doc/user/lua.html for example.

I am incrementally migrating more and more pages to "flow" layout, but meanwhile any help with the CSS is welcome. (But please check the results carefully; we've had several half-baked attempts already.)

Meanwhile this is tracked in https://github.com/neovim/neovim.github.io/issues/288
